services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres_password

    web:
        build: .
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
